---
title: "viz_part_1"
author: "Sneha Mehta"
date: "2022-09-29"
output: github_document
---
```{r setup}
library(tidyverse)
library(ggridges)
```

Importing Data:
```{r import weather}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```
Creating scatterplot
```{r scatter}
ggplot(weather_df, aes(x = tmin, y = tmax)) #blank plot

#adding geompoints

ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```
Let's make the same scatterplot but make it differently
```{r piping}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

#can use this to combine multiple steps
#filtering Central Park only
weather_df %>%
  drop_na() %>% 
  filter(name == "CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```
Let's keep making the same plot but different
```{r}
weather_scatterplot = weather_df %>% 
  drop_na() %>% 
  ggplot(aes(x = tmin, y = tmax))

weather_scatterplot + geom_point()
```
Adding Color:
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax))+
  geom_point(aes(color = name))

#adding smooth curve
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax))+
  geom_point(aes(color = name)) +
  geom_smooth()

#color coding smooth line
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name))+
  geom_point(alpha = 0.3) +
  geom_smooth()

weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name))+
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)
```
Make separate panels
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name))+
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

```

tmin vs tmax is boring, looking at seasonal trends
```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth( se = FALSE) + 
  facet_grid(. ~ name) +
  theme(axis.text = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

